export const FETCH_VIDEO = 'FETCH_VIDEO';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILED = 'FETCH_VIDEO_FAILED';

export const SHARE_VIDEO = 'SHARE_VIDEO';
export const SHARE_VIDEO_SUCCESS = 'SHARE_VIDEO_SUCCESS';
export const SHARE_VIDEO_FAILED = 'SHARE_VIDEO_FAILED';